"""M1: download equities (yfinance), macro (FRED), and GDELT news; write DATA_CARD.md.

Usage:
    python download_data.py                       # everything
    python download_data.py --skip-gdelt           # equities + macro only (fast)
    python download_data.py --only-gdelt           # GDELT only (slow, rate-limited)
    python download_data.py --gdelt-tickers AAPL MSFT
"""
from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd

from src.data.gdelt_raw import download_gdelt_news_for_ticker
from src.data.loaders import download_equities, download_macro
from src.utils.config import load_config

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)


def write_data_card(
    cfg: dict,
    raw_dir: Path,
    equities: dict[str, pd.DataFrame],
    macro: dict[str, pd.DataFrame],
    gdelt_summary: dict[str, dict] | None,
    out_path: Path,
) -> None:
    lines = ["# DATA_CARD.md", "", "Auto-generated by `download_data.py`. Describes coverage, gaps, and known limitations.", ""]

    lines.append("## Equities (yfinance, daily OHLCV, auto-adjusted)")
    lines.append("")
    lines.append("| Ticker | Rows | Start | End | Missing trading days (approx) |")
    lines.append("|---|---|---|---|---|")
    for ticker, df in equities.items():
        if df.empty:
            lines.append(f"| {ticker} | 0 | - | - | ALL (download failed) |")
            continue
        start, end = df.index.min(), df.index.max()
        expected = pd.bdate_range(start, end)
        missing = len(expected) - len(df)
        lines.append(f"| {ticker} | {len(df)} | {start.date()} | {end.date()} | {missing} |")
    lines.append("")

    lines.append("## Macro (FRED, native release frequency, no API key required)")
    lines.append("")
    lines.append("| Series | Rows | Start | End | Native frequency |")
    lines.append("|---|---|---|---|---|")
    freq_hint = {
        "cpi": "monthly", "unemployment": "monthly", "fed_funds": "daily",
        "yield_10y": "daily", "consumer_sentiment": "monthly", "industrial_production": "monthly",
    }
    for name, df in macro.items():
        if df.empty:
            lines.append(f"| {name} | 0 | - | - | - |")
            continue
        start, end = df.index.min(), df.index.max()
        lines.append(f"| {name} | {len(df)} | {start.date()} | {end.date()} | {freq_hint.get(name, 'unknown')} |")
    lines.append("")

    lines.append("## Sentiment (GDELT 2.0 DOC API + FinBERT scoring in M2)")
    lines.append("")
    lines.append(
        "**Known limitation (documented explicitly per project instructions):** the GDELT 2.0 "
        "DOC API enforces a strict rate limit (observed: HTTP 429 even with 30-60s gaps between "
        "requests on this environment's shared egress IP). To keep the full "
        f"{cfg['data']['start_date']}-present pull tractable, article queries use two "
        "resolutions:\n"
        f"- **Daily** queries inside the sentiment-equity case study window "
        f"({cfg['data']['case_study_window'][0]} to {cfg['data']['case_study_window'][1]}).\n"
        "- **Monthly** queries for the remainder of the full historical span (coarser sentiment "
        "resolution outside the case study window; per-day sentiment features outside this window "
        "are forward-filled from the enclosing month's aggregate in M2).\n\n"
        "GDELT's DOC 2.0 full-text search index also has materially better English-language "
        "coverage from ~2017 onward; article volume for 2016 may be sparse.\n"
    )
    if gdelt_summary:
        lines.append("| Ticker | Articles cached | Windows queried | Windows with zero articles |")
        lines.append("|---|---|---|---|")
        for ticker, s in gdelt_summary.items():
            lines.append(f"| {ticker} | {s['n_articles']} | {s['n_windows']} | {s['n_empty_windows']} |")
        lines.append("")
    else:
        lines.append("_GDELT step was skipped in this run (see run flags)._\n")

    lines.append("## Missingness policy")
    lines.append("")
    lines.append(
        "Days/windows with zero retrieved news articles are filled with neutral sentiment "
        "(signed_score = 0) plus an explicit `has_news=0` missingness flag, applied in M2 "
        "(`src/data/sentiment_gdelt_finbert.py`), not at raw-download time."
    )
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %s", out_path)


def write_sanity_plots(equities: dict[str, pd.DataFrame], figures_dir: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    figures_dir.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(10, 6))
    for ticker, df in equities.items():
        if df.empty or "Close" not in df.columns:
            continue
        norm = df["Close"] / df["Close"].iloc[0] * 100
        ax.plot(df.index, norm, label=ticker)
    ax.set_title("Normalized close price (start=100)")
    ax.set_xlabel("Date")
    ax.set_ylabel("Index (start=100)")
    ax.legend()
    fig.tight_layout()
    fig.savefig(figures_dir / "m1_equities_sanity.png", dpi=150)
    fig.savefig(figures_dir / "m1_equities_sanity.pdf")
    plt.close(fig)
    logger.info("Wrote sanity plot -> %s", figures_dir / "m1_equities_sanity.png")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-equities", action="store_true")
    parser.add_argument("--skip-macro", action="store_true")
    parser.add_argument("--skip-gdelt", action="store_true")
    parser.add_argument("--only-gdelt", action="store_true")
    parser.add_argument("--gdelt-tickers", nargs="*", default=None)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    cfg = load_config("config.yaml")
    raw_dir = Path(cfg["paths"]["raw_dir"])
    figures_dir = Path(cfg["paths"]["figures_dir"])
    raw_dir.mkdir(parents=True, exist_ok=True)

    all_tickers = cfg["universe"]["tickers"] + [cfg["universe"]["benchmark"]]

    equities: dict[str, pd.DataFrame] = {}
    macro: dict[str, pd.DataFrame] = {}

    if not args.only_gdelt and not args.skip_equities:
        equities = download_equities(
            all_tickers, cfg["data"]["start_date"], cfg["data"]["end_date"], raw_dir, force=args.force
        )
        write_sanity_plots(equities, figures_dir)

    if not args.only_gdelt and not args.skip_macro:
        macro = download_macro(
            cfg["macro"]["fred_series"], cfg["data"]["start_date"], cfg["data"]["end_date"], raw_dir, force=args.force
        )

    gdelt_summary = None
    if not args.skip_gdelt:
        gdelt_summary = {}
        tickers = args.gdelt_tickers or cfg["universe"]["tickers"]
        sc = cfg["sentiment"]
        for ticker in tickers:
            keywords = sc["keywords"].get(ticker, [ticker])
            df = download_gdelt_news_for_ticker(
                ticker=ticker,
                keywords=keywords,
                start=cfg["data"]["start_date"],
                end=cfg["data"]["end_date"],
                case_study_window=tuple(cfg["data"]["case_study_window"]),
                raw_dir=raw_dir,
                max_records=sc["max_records_per_query"],
                rate_limit_sleep_sec=sc["rate_limit_sleep_sec"],
                retry_max=sc["retry_max"],
                retry_backoff_sec=sc["retry_backoff_sec"],
                retry_backoff_max_sec=sc["retry_backoff_max_sec"],
                min_start=sc.get("gdelt_min_start", "2017-01-01"),
            )
            n_windows = len(list((raw_dir / "gdelt" / ticker).glob("*.csv")))
            n_empty = sum(
                1 for p in (raw_dir / "gdelt" / ticker).glob("*.csv")
                if pd.read_csv(p).empty
            )
            gdelt_summary[ticker] = {
                "n_articles": len(df), "n_windows": n_windows, "n_empty_windows": n_empty,
            }
            logger.info("GDELT done for %s: %s", ticker, gdelt_summary[ticker])

    if equities or macro or gdelt_summary:
        write_data_card(cfg, raw_dir, equities, macro, gdelt_summary, Path("DATA_CARD.md"))


if __name__ == "__main__":
    main()
